language: jvm
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
  - dataflow

jvm_args:
  # -DentityExpansionLimit=0 le dice al parser XML del JDK que no tenga límite
  # para la expansión de entidades, permitiendo que el ataque "Billion Laughs" proceda.
  - "-DentityExpansionLimit=0"